//! Core data types shared across all providers.
//!
//! These types form the provider-agnostic contract: callers build a
//! [`ChatRequest`] and receive a [`ChatResponse`] regardless of which
//! underlying LLM API is used.

use serde::{Deserialize, Serialize};

//  Role

/// The role of a participant in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A system-level instruction message.
    System,
    /// A message from the human user.
    User,
    /// A message generated by the assistant.
    Assistant,
}

//  Message

/// A single message in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    /// Who sent this message.
    pub role: Role,
    /// The text content of the message.
    pub content: String,
}

impl Message {
    /// Construct a new [`Message`].
    ///
    /// # Arguments
    /// * `role`  -  who is sending this message
    /// * `content`  -  the text content
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::{Message, Role};
    /// let msg = Message::new(Role::User, "Hello, world!");
    /// assert_eq!(msg.role, Role::User);
    /// ```
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
        }
    }

    /// Shorthand for creating a [`Role::System`] message.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::{Message, Role};
    /// let msg = Message::system("You are a helpful assistant.");
    /// assert_eq!(msg.role, Role::System);
    /// ```
    pub fn system(content: impl Into<String>) -> Self {
        Self::new(Role::System, content)
    }

    /// Shorthand for creating a [`Role::User`] message.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::{Message, Role};
    /// let msg = Message::user("What is 2+2?");
    /// assert_eq!(msg.role, Role::User);
    /// ```
    pub fn user(content: impl Into<String>) -> Self {
        Self::new(Role::User, content)
    }

    /// Shorthand for creating a [`Role::Assistant`] message.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::{Message, Role};
    /// let msg = Message::assistant("It is 4.");
    /// assert_eq!(msg.role, Role::Assistant);
    /// ```
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::new(Role::Assistant, content)
    }
}

//  Model

/// All supported LLM models across OpenAI and Anthropic.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Model {
    // OpenAI models
    /// GPT-4o  -  OpenAI's latest multimodal flagship model.
    #[serde(rename = "gpt-4o")]
    Gpt4o,
    /// GPT-4o mini  -  fast and cost-efficient.
    #[serde(rename = "gpt-4o-mini")]
    Gpt4oMini,
    /// GPT-4 Turbo  -  previous-generation high-capability model.
    #[serde(rename = "gpt-4-turbo")]
    Gpt4Turbo,
    /// GPT-3.5 Turbo  -  fast, cheap, suitable for simple tasks.
    #[serde(rename = "gpt-3.5-turbo")]
    Gpt35Turbo,
    /// o1  -  OpenAI's reasoning model.
    #[serde(rename = "o1")]
    O1,
    /// o1-mini  -  smaller, faster reasoning model.
    #[serde(rename = "o1-mini")]
    O1Mini,
    /// o3-mini  -  latest compact reasoning model.
    #[serde(rename = "o3-mini")]
    O3Mini,

    // Anthropic models
    /// Claude 3.5 Sonnet  -  Anthropic's best balance of speed and capability.
    #[serde(rename = "claude-3-5-sonnet-20241022")]
    Claude35Sonnet,
    /// Claude 3.5 Haiku  -  Anthropic's fastest model.
    #[serde(rename = "claude-3-5-haiku-20241022")]
    Claude35Haiku,
    /// Claude 3 Opus  -  Anthropic's most capable model.
    #[serde(rename = "claude-3-opus-20240229")]
    Claude3Opus,
    /// Claude 3 Sonnet  -  balanced Anthropic model.
    #[serde(rename = "claude-3-sonnet-20240229")]
    Claude3Sonnet,
    /// Claude 3 Haiku  -  smallest and fastest Anthropic model.
    #[serde(rename = "claude-3-haiku-20240307")]
    Claude3Haiku,

    /// A custom model identifier not in the standard list.
    #[serde(untagged)]
    Custom(String),
}

impl Model {
    /// Returns the API identifier string for this model.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::Model;
    /// assert_eq!(Model::Gpt4o.as_str(), "gpt-4o");
    /// assert_eq!(Model::Claude35Sonnet.as_str(), "claude-3-5-sonnet-20241022");
    /// ```
    pub fn as_str(&self) -> &str {
        match self {
            Model::Gpt4o => "gpt-4o",
            Model::Gpt4oMini => "gpt-4o-mini",
            Model::Gpt4Turbo => "gpt-4-turbo",
            Model::Gpt35Turbo => "gpt-3.5-turbo",
            Model::O1 => "o1",
            Model::O1Mini => "o1-mini",
            Model::O3Mini => "o3-mini",
            Model::Claude35Sonnet => "claude-3-5-sonnet-20241022",
            Model::Claude35Haiku => "claude-3-5-haiku-20241022",
            Model::Claude3Opus => "claude-3-opus-20240229",
            Model::Claude3Sonnet => "claude-3-sonnet-20240229",
            Model::Claude3Haiku => "claude-3-haiku-20240307",
            Model::Custom(s) => s.as_str(),
        }
    }

    /// Returns `true` if this is an OpenAI-hosted model.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::Model;
    /// assert!(Model::Gpt4o.is_openai());
    /// assert!(!Model::Claude35Sonnet.is_openai());
    /// ```
    pub fn is_openai(&self) -> bool {
        matches!(
            self,
            Model::Gpt4o
                | Model::Gpt4oMini
                | Model::Gpt4Turbo
                | Model::Gpt35Turbo
                | Model::O1
                | Model::O1Mini
                | Model::O3Mini
        )
    }

    /// Returns `true` if this is an Anthropic-hosted model.
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::Model;
    /// assert!(Model::Claude35Sonnet.is_anthropic());
    /// assert!(!Model::Gpt4o.is_anthropic());
    /// ```
    pub fn is_anthropic(&self) -> bool {
        matches!(
            self,
            Model::Claude35Sonnet
                | Model::Claude35Haiku
                | Model::Claude3Opus
                | Model::Claude3Sonnet
                | Model::Claude3Haiku
        )
    }
}

//  ChatRequest

/// A request to a chat completion endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    /// The model to use for this request.
    pub model: Model,
    /// The conversation history, including the new user turn.
    pub messages: Vec<Message>,
    /// Maximum number of tokens the model may generate.
    pub max_tokens: Option<u32>,
    /// Sampling temperature in `[0, 2]`. Lower = more deterministic.
    pub temperature: Option<f32>,
    /// Whether to request a streaming response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
}

impl ChatRequest {
    /// Create a new [`ChatRequest`] with the given model and messages.
    ///
    /// # Arguments
    /// * `model`  -  which LLM to call
    /// * `messages`  -  the full conversation context
    ///
    /// # Example
    /// ```rust
    /// # use tokio_llm::types::{ChatRequest, Message, Model};
    /// let req = ChatRequest::new(Model::Gpt4oMini, vec![Message::user("Hi")]);
    /// assert!(req.max_tokens.is_none());
    /// ```
    pub fn new(model: Model, messages: Vec<Message>) -> Self {
        Self {
            model,
            messages,
            max_tokens: None,
            temperature: None,
            stream: None,
        }
    }

    /// Set the maximum number of tokens to generate.
    pub fn with_max_tokens(mut self, max_tokens: u32) -> Self {
        self.max_tokens = Some(max_tokens);
        self
    }

    /// Set the sampling temperature.
    pub fn with_temperature(mut self, temperature: f32) -> Self {
        self.temperature = Some(temperature);
        self
    }
}

//  Usage

/// Token usage and estimated cost for a single API call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct Usage {
    /// Number of tokens in the prompt (input).
    pub prompt_tokens: u32,
    /// Number of tokens generated (output).
    pub completion_tokens: u32,
    /// Total tokens (`prompt_tokens + completion_tokens`).
    pub total_tokens: u32,
    /// Estimated cost in USD for this request.
    pub cost_usd: f64,
}

impl Usage {
    /// Construct a [`Usage`] record.
    ///
    /// # Arguments
    /// * `prompt_tokens`  -  input token count
    /// * `completion_tokens`  -  output token count
    /// * `cost_usd`  -  computed cost in USD
    pub fn new(prompt_tokens: u32, completion_tokens: u32, cost_usd: f64) -> Self {
        Self {
            prompt_tokens,
            completion_tokens,
            total_tokens: prompt_tokens + completion_tokens,
            cost_usd,
        }
    }
}

//  ChatResponse

/// A complete (non-streaming) response from a chat completion endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    /// The text content of the assistant's reply.
    pub content: String,
    /// The model that generated this response.
    pub model: String,
    /// Token usage and cost information.
    pub usage: Usage,
    /// Provider-assigned request identifier, if available.
    pub request_id: Option<String>,
}

//  StreamChunk

/// A single chunk received from a streaming chat completion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamChunk {
    /// Incremental text delta for this chunk (may be empty on the final chunk).
    pub delta: String,
    /// Whether this is the final chunk in the stream.
    pub is_final: bool,
    /// Final usage stats  -  only populated on the last chunk, if the provider sends them.
    pub usage: Option<Usage>,
}

impl StreamChunk {
    /// Create a non-final content delta chunk.
    pub fn delta(text: impl Into<String>) -> Self {
        Self {
            delta: text.into(),
            is_final: false,
            usage: None,
        }
    }

    /// Create the final chunk, optionally carrying usage stats.
    pub fn final_chunk(usage: Option<Usage>) -> Self {
        Self {
            delta: String::new(),
            is_final: true,
            usage,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    //  Role tests

    #[test]
    fn test_role_serializes_lowercase() {
        assert_eq!(
            serde_json::to_string(&Role::User).unwrap_or_default(),
            "\"user\""
        );
        assert_eq!(
            serde_json::to_string(&Role::System).unwrap_or_default(),
            "\"system\""
        );
        assert_eq!(
            serde_json::to_string(&Role::Assistant).unwrap_or_default(),
            "\"assistant\""
        );
    }

    #[test]
    fn test_role_deserializes_from_lowercase() {
        let r: Role = serde_json::from_str("\"user\"").unwrap_or(Role::System);
        assert_eq!(r, Role::User);
    }

    #[test]
    fn test_role_equality() {
        assert_eq!(Role::User, Role::User);
        assert_ne!(Role::User, Role::Assistant);
    }

    //  Message tests

    #[test]
    fn test_message_new_sets_role_and_content() {
        let m = Message::new(Role::User, "hello");
        assert_eq!(m.role, Role::User);
        assert_eq!(m.content, "hello");
    }

    #[test]
    fn test_message_system_shorthand() {
        let m = Message::system("be helpful");
        assert_eq!(m.role, Role::System);
        assert_eq!(m.content, "be helpful");
    }

    #[test]
    fn test_message_user_shorthand() {
        let m = Message::user("what is rust?");
        assert_eq!(m.role, Role::User);
    }

    #[test]
    fn test_message_assistant_shorthand() {
        let m = Message::assistant("Rust is a systems language.");
        assert_eq!(m.role, Role::Assistant);
    }

    #[test]
    fn test_message_round_trips_json() {
        let original = Message::user("test content");
        let json = serde_json::to_string(&original).unwrap_or_default();
        let decoded: Message = serde_json::from_str(&json).unwrap_or_else(|_| Message::system(""));
        assert_eq!(decoded, original);
    }

    #[test]
    fn test_message_content_accepts_string_owned() {
        let s = String::from("owned string");
        let m = Message::user(s);
        assert_eq!(m.content, "owned string");
    }

    //  Model tests

    #[test]
    fn test_model_as_str_gpt4o() {
        assert_eq!(Model::Gpt4o.as_str(), "gpt-4o");
    }

    #[test]
    fn test_model_as_str_claude35_sonnet() {
        assert_eq!(Model::Claude35Sonnet.as_str(), "claude-3-5-sonnet-20241022");
    }

    #[test]
    fn test_model_as_str_custom() {
        let m = Model::Custom("my-fine-tuned-model".into());
        assert_eq!(m.as_str(), "my-fine-tuned-model");
    }

    #[test]
    fn test_model_is_openai_gpt4o_true() {
        assert!(Model::Gpt4o.is_openai());
    }

    #[test]
    fn test_model_is_openai_claude_false() {
        assert!(!Model::Claude35Sonnet.is_openai());
    }

    #[test]
    fn test_model_is_anthropic_claude_true() {
        assert!(Model::Claude35Sonnet.is_anthropic());
    }

    #[test]
    fn test_model_is_anthropic_gpt_false() {
        assert!(!Model::Gpt4o.is_anthropic());
    }

    #[test]
    fn test_model_custom_is_neither_openai_nor_anthropic() {
        let m = Model::Custom("llama-3".into());
        assert!(!m.is_openai());
        assert!(!m.is_anthropic());
    }

    #[test]
    fn test_all_openai_models_report_openai() {
        let models = [
            Model::Gpt4o,
            Model::Gpt4oMini,
            Model::Gpt4Turbo,
            Model::Gpt35Turbo,
            Model::O1,
            Model::O1Mini,
            Model::O3Mini,
        ];
        for m in &models {
            assert!(m.is_openai(), "{} should be openai", m.as_str());
        }
    }

    #[test]
    fn test_all_anthropic_models_report_anthropic() {
        let models = [
            Model::Claude35Sonnet,
            Model::Claude35Haiku,
            Model::Claude3Opus,
            Model::Claude3Sonnet,
            Model::Claude3Haiku,
        ];
        for m in &models {
            assert!(m.is_anthropic(), "{} should be anthropic", m.as_str());
        }
    }

    //  ChatRequest tests

    #[test]
    fn test_chat_request_new_defaults() {
        let req = ChatRequest::new(Model::Gpt4oMini, vec![Message::user("hi")]);
        assert!(req.max_tokens.is_none());
        assert!(req.temperature.is_none());
        assert!(req.stream.is_none());
    }

    #[test]
    fn test_chat_request_with_max_tokens() {
        let req = ChatRequest::new(Model::Gpt4oMini, vec![]).with_max_tokens(512);
        assert_eq!(req.max_tokens, Some(512));
    }

    #[test]
    fn test_chat_request_with_temperature() {
        let req = ChatRequest::new(Model::Gpt4oMini, vec![]).with_temperature(0.7);
        assert!((req.temperature.unwrap_or(0.0) - 0.7).abs() < f32::EPSILON);
    }

    #[test]
    fn test_chat_request_builder_chaining() {
        let req = ChatRequest::new(Model::Gpt4o, vec![Message::user("x")])
            .with_max_tokens(100)
            .with_temperature(0.5);
        assert_eq!(req.max_tokens, Some(100));
        assert!((req.temperature.unwrap_or(0.0) - 0.5).abs() < f32::EPSILON);
    }

    //  Usage tests

    #[test]
    fn test_usage_new_computes_total_tokens() {
        let u = Usage::new(100, 50, 0.001);
        assert_eq!(u.total_tokens, 150);
    }

    #[test]
    fn test_usage_cost_usd_stored_exactly() {
        let u = Usage::new(0, 0, 0.12345);
        assert!((u.cost_usd - 0.12345).abs() < f64::EPSILON);
    }

    #[test]
    fn test_usage_default_is_zeroed() {
        let u = Usage::default();
        assert_eq!(u.prompt_tokens, 0);
        assert_eq!(u.completion_tokens, 0);
        assert_eq!(u.total_tokens, 0);
        assert_eq!(u.cost_usd, 0.0);
    }

    //  StreamChunk tests

    #[test]
    fn test_stream_chunk_delta_not_final() {
        let c = StreamChunk::delta("hello");
        assert_eq!(c.delta, "hello");
        assert!(!c.is_final);
        assert!(c.usage.is_none());
    }

    #[test]
    fn test_stream_chunk_final_chunk_is_final() {
        let c = StreamChunk::final_chunk(None);
        assert!(c.is_final);
        assert!(c.delta.is_empty());
    }

    #[test]
    fn test_stream_chunk_final_chunk_with_usage() {
        let usage = Usage::new(10, 5, 0.001);
        let c = StreamChunk::final_chunk(Some(usage.clone()));
        assert!(c.is_final);
        assert_eq!(c.usage.unwrap_or_default().total_tokens, 15);
    }
}
